apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-ingress
  namespace: monitoring
spec:
  rules:
  - host: thanos-querier.cluster.cncf.ir
    http:
      paths:
      - backend:
          service:
            name: thanos-querier
            port:
              number: 9090
        path: /
        pathType: Prefix
